### ISSUE TITLE
Backlight indicator is not saving your settings on Ubuntu 16.04

### ISSUE THREAD

**Issue by ghost** [atareao/backlight-indicator#1]
Dear,

The backlight-indicator is not saving any settings in Ubuntu 16.04. Here's the error showed on console after launch the app.

/opt/extras.ubuntu.com/backlight-indicator/share/backlight-indicator/backlightindicator.py:25: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/opt/extras.ubuntu.com/backlight-indicator/share/backlight-indicator/backlightindicator.py:28: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator
/opt/extras.ubuntu.com/backlight-indicator/share/backlight-indicator/backlightindicator.py:29: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
[Errno 2] No translation file found for domain: 'backlight-indicator'
/opt/extras.ubuntu.com/backlight-indicator/share/backlight-indicator/webcam.py:25: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gst

(backlight-indicator:24651): Gtk-WARNING **: Can't set a parent on widget which has a parent

Thanks.

**Comment by atareao** [comment]
Fixed
